# Generated by Django 2.2 on 2019-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agtagents',
            fields=[
                ('agentid', models.IntegerField(db_column='agentID', primary_key=True, serialize=False)),
                ('divisionid', models.IntegerField(blank=True, db_column='divisionID', null=True)),
                ('corporationid', models.IntegerField(blank=True, db_column='corporationID', null=True)),
                ('locationid', models.IntegerField(blank=True, db_column='locationID', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('agenttypeid', models.IntegerField(blank=True, db_column='agentTypeID', null=True)),
                ('islocator', models.IntegerField(blank=True, db_column='isLocator', null=True)),
            ],
            options={
                'db_table': 'agtAgents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agtagenttypes',
            fields=[
                ('agenttypeid', models.IntegerField(db_column='agentTypeID', primary_key=True, serialize=False)),
                ('agenttype', models.CharField(blank=True, db_column='agentType', max_length=50, null=True)),
            ],
            options={
                'db_table': 'agtAgentTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agtresearchagents',
            fields=[
                ('agentid', models.IntegerField(db_column='agentID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='typeID')),
            ],
            options={
                'db_table': 'agtResearchAgents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certcerts',
            fields=[
                ('certid', models.IntegerField(db_column='certID', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('groupid', models.IntegerField(blank=True, db_column='groupID', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'certCerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certmasteries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('masterylevel', models.IntegerField(blank=True, db_column='masteryLevel', null=True)),
                ('certid', models.IntegerField(blank=True, db_column='certID', null=True)),
            ],
            options={
                'db_table': 'certMasteries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certid', models.IntegerField(blank=True, db_column='certID', null=True)),
                ('skillid', models.IntegerField(blank=True, db_column='skillID', null=True)),
                ('certlevelint', models.IntegerField(blank=True, db_column='certLevelInt', null=True)),
                ('skilllevel', models.IntegerField(blank=True, db_column='skillLevel', null=True)),
                ('certleveltext', models.CharField(blank=True, db_column='certLevelText', max_length=8, null=True)),
            ],
            options={
                'db_table': 'certSkills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrancestries',
            fields=[
                ('ancestryid', models.IntegerField(db_column='ancestryID', primary_key=True, serialize=False)),
                ('ancestryname', models.CharField(blank=True, db_column='ancestryName', max_length=100, null=True)),
                ('bloodlineid', models.IntegerField(blank=True, db_column='bloodlineID', null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('perception', models.IntegerField(blank=True, null=True)),
                ('willpower', models.IntegerField(blank=True, null=True)),
                ('charisma', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('shortdescription', models.CharField(blank=True, db_column='shortDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'chrAncestries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrattributes',
            fields=[
                ('attributeid', models.IntegerField(db_column='attributeID', primary_key=True, serialize=False)),
                ('attributename', models.CharField(blank=True, db_column='attributeName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('shortdescription', models.CharField(blank=True, db_column='shortDescription', max_length=500, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'chrAttributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrbloodlines',
            fields=[
                ('bloodlineid', models.IntegerField(db_column='bloodlineID', primary_key=True, serialize=False)),
                ('bloodlinename', models.CharField(blank=True, db_column='bloodlineName', max_length=100, null=True)),
                ('raceid', models.IntegerField(blank=True, db_column='raceID', null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('maledescription', models.CharField(blank=True, db_column='maleDescription', max_length=1000, null=True)),
                ('femaledescription', models.CharField(blank=True, db_column='femaleDescription', max_length=1000, null=True)),
                ('shiptypeid', models.IntegerField(blank=True, db_column='shipTypeID', null=True)),
                ('corporationid', models.IntegerField(blank=True, db_column='corporationID', null=True)),
                ('perception', models.IntegerField(blank=True, null=True)),
                ('willpower', models.IntegerField(blank=True, null=True)),
                ('charisma', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('shortdescription', models.CharField(blank=True, db_column='shortDescription', max_length=500, null=True)),
                ('shortmaledescription', models.CharField(blank=True, db_column='shortMaleDescription', max_length=500, null=True)),
                ('shortfemaledescription', models.CharField(blank=True, db_column='shortFemaleDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'chrBloodlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrfactions',
            fields=[
                ('factionid', models.IntegerField(db_column='factionID', primary_key=True, serialize=False)),
                ('factionname', models.CharField(blank=True, db_column='factionName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('raceids', models.IntegerField(blank=True, db_column='raceIDs', null=True)),
                ('solarsystemid', models.IntegerField(blank=True, db_column='solarSystemID', null=True)),
                ('corporationid', models.IntegerField(blank=True, db_column='corporationID', null=True)),
                ('sizefactor', models.FloatField(blank=True, db_column='sizeFactor', null=True)),
                ('stationcount', models.IntegerField(blank=True, db_column='stationCount', null=True)),
                ('stationsystemcount', models.IntegerField(blank=True, db_column='stationSystemCount', null=True)),
                ('militiacorporationid', models.IntegerField(blank=True, db_column='militiaCorporationID', null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
            ],
            options={
                'db_table': 'chrFactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrraces',
            fields=[
                ('raceid', models.IntegerField(db_column='raceID', primary_key=True, serialize=False)),
                ('racename', models.CharField(blank=True, db_column='raceName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('shortdescription', models.CharField(blank=True, db_column='shortDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'chrRaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpactivities',
            fields=[
                ('activityid', models.IntegerField(db_column='activityID', primary_key=True, serialize=False)),
                ('activityname', models.CharField(blank=True, db_column='activityName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'crpActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationdivisions',
            fields=[
                ('corporationid', models.IntegerField(db_column='corporationID', primary_key=True, serialize=False)),
                ('divisionid', models.IntegerField(db_column='divisionID')),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crpNPCCorporationDivisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationresearchfields',
            fields=[
                ('skillid', models.IntegerField(db_column='skillID', primary_key=True, serialize=False)),
                ('corporationid', models.IntegerField(db_column='corporationID')),
            ],
            options={
                'db_table': 'crpNPCCorporationResearchFields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporations',
            fields=[
                ('corporationid', models.IntegerField(db_column='corporationID', primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=1, null=True)),
                ('extent', models.CharField(blank=True, max_length=1, null=True)),
                ('solarsystemid', models.IntegerField(blank=True, db_column='solarSystemID', null=True)),
                ('investorid1', models.IntegerField(blank=True, db_column='investorID1', null=True)),
                ('investorshares1', models.IntegerField(blank=True, db_column='investorShares1', null=True)),
                ('investorid2', models.IntegerField(blank=True, db_column='investorID2', null=True)),
                ('investorshares2', models.IntegerField(blank=True, db_column='investorShares2', null=True)),
                ('investorid3', models.IntegerField(blank=True, db_column='investorID3', null=True)),
                ('investorshares3', models.IntegerField(blank=True, db_column='investorShares3', null=True)),
                ('investorid4', models.IntegerField(blank=True, db_column='investorID4', null=True)),
                ('investorshares4', models.IntegerField(blank=True, db_column='investorShares4', null=True)),
                ('friendid', models.IntegerField(blank=True, db_column='friendID', null=True)),
                ('enemyid', models.IntegerField(blank=True, db_column='enemyID', null=True)),
                ('publicshares', models.IntegerField(blank=True, db_column='publicShares', null=True)),
                ('initialprice', models.IntegerField(blank=True, db_column='initialPrice', null=True)),
                ('minsecurity', models.FloatField(blank=True, db_column='minSecurity', null=True)),
                ('scattered', models.IntegerField(blank=True, null=True)),
                ('fringe', models.IntegerField(blank=True, null=True)),
                ('corridor', models.IntegerField(blank=True, null=True)),
                ('hub', models.IntegerField(blank=True, null=True)),
                ('border', models.IntegerField(blank=True, null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('sizefactor', models.FloatField(blank=True, db_column='sizeFactor', null=True)),
                ('stationcount', models.IntegerField(blank=True, db_column='stationCount', null=True)),
                ('stationsystemcount', models.IntegerField(blank=True, db_column='stationSystemCount', null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
            ],
            options={
                'db_table': 'crpNPCCorporations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationtrades',
            fields=[
                ('corporationid', models.IntegerField(db_column='corporationID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='typeID')),
            ],
            options={
                'db_table': 'crpNPCCorporationTrades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpcdivisions',
            fields=[
                ('divisionid', models.IntegerField(db_column='divisionID', primary_key=True, serialize=False)),
                ('divisionname', models.CharField(blank=True, db_column='divisionName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('leadertype', models.CharField(blank=True, db_column='leaderType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'crpNPCDivisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmattributecategories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=50, null=True)),
                ('categorydescription', models.CharField(blank=True, db_column='categoryDescription', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dgmAttributeCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmattributetypes',
            fields=[
                ('attributeid', models.IntegerField(db_column='attributeID', primary_key=True, serialize=False)),
                ('attributename', models.CharField(blank=True, db_column='attributeName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('defaultvalue', models.FloatField(blank=True, db_column='defaultValue', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
                ('displayname', models.CharField(blank=True, db_column='displayName', max_length=150, null=True)),
                ('unitid', models.IntegerField(blank=True, db_column='unitID', null=True)),
                ('stackable', models.IntegerField(blank=True, null=True)),
                ('highisgood', models.IntegerField(blank=True, db_column='highIsGood', null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryID', null=True)),
            ],
            options={
                'db_table': 'dgmAttributeTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmeffects',
            fields=[
                ('effectid', models.IntegerField(db_column='effectID', primary_key=True, serialize=False)),
                ('effectname', models.CharField(blank=True, db_column='effectName', max_length=400, null=True)),
                ('effectcategory', models.IntegerField(blank=True, db_column='effectCategory', null=True)),
                ('preexpression', models.IntegerField(blank=True, db_column='preExpression', null=True)),
                ('postexpression', models.IntegerField(blank=True, db_column='postExpression', null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('guid', models.CharField(blank=True, max_length=60, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('isoffensive', models.IntegerField(blank=True, db_column='isOffensive', null=True)),
                ('isassistance', models.IntegerField(blank=True, db_column='isAssistance', null=True)),
                ('durationattributeid', models.IntegerField(blank=True, db_column='durationAttributeID', null=True)),
                ('trackingspeedattributeid', models.IntegerField(blank=True, db_column='trackingSpeedAttributeID', null=True)),
                ('dischargeattributeid', models.IntegerField(blank=True, db_column='dischargeAttributeID', null=True)),
                ('rangeattributeid', models.IntegerField(blank=True, db_column='rangeAttributeID', null=True)),
                ('falloffattributeid', models.IntegerField(blank=True, db_column='falloffAttributeID', null=True)),
                ('disallowautorepeat', models.IntegerField(blank=True, db_column='disallowAutoRepeat', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
                ('displayname', models.CharField(blank=True, db_column='displayName', max_length=100, null=True)),
                ('iswarpsafe', models.IntegerField(blank=True, db_column='isWarpSafe', null=True)),
                ('rangechance', models.IntegerField(blank=True, db_column='rangeChance', null=True)),
                ('electronicchance', models.IntegerField(blank=True, db_column='electronicChance', null=True)),
                ('propulsionchance', models.IntegerField(blank=True, db_column='propulsionChance', null=True)),
                ('distribution', models.IntegerField(blank=True, null=True)),
                ('sfxname', models.CharField(blank=True, db_column='sfxName', max_length=20, null=True)),
                ('npcusagechanceattributeid', models.IntegerField(blank=True, db_column='npcUsageChanceAttributeID', null=True)),
                ('npcactivationchanceattributeid', models.IntegerField(blank=True, db_column='npcActivationChanceAttributeID', null=True)),
                ('fittingusagechanceattributeid', models.IntegerField(blank=True, db_column='fittingUsageChanceAttributeID', null=True)),
                ('modifierinfo', models.TextField(blank=True, db_column='modifierInfo', null=True)),
            ],
            options={
                'db_table': 'dgmEffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmexpressions',
            fields=[
                ('expressionid', models.IntegerField(db_column='expressionID', primary_key=True, serialize=False)),
                ('operandid', models.IntegerField(blank=True, db_column='operandID', null=True)),
                ('arg1', models.IntegerField(blank=True, null=True)),
                ('arg2', models.IntegerField(blank=True, null=True)),
                ('expressionvalue', models.CharField(blank=True, db_column='expressionValue', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('expressionname', models.CharField(blank=True, db_column='expressionName', max_length=500, null=True)),
                ('expressiontypeid', models.IntegerField(blank=True, db_column='expressionTypeID', null=True)),
                ('expressiongroupid', models.IntegerField(blank=True, db_column='expressionGroupID', null=True)),
                ('expressionattributeid', models.IntegerField(blank=True, db_column='expressionAttributeID', null=True)),
            ],
            options={
                'db_table': 'dgmExpressions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmtypeattributes',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('attributeid', models.IntegerField(db_column='attributeID')),
                ('valueint', models.IntegerField(blank=True, db_column='valueInt', null=True)),
                ('valuefloat', models.FloatField(blank=True, db_column='valueFloat', null=True)),
            ],
            options={
                'db_table': 'dgmTypeAttributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmtypeeffects',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('effectid', models.IntegerField(db_column='effectID')),
                ('isdefault', models.IntegerField(blank=True, db_column='isDefault', null=True)),
            ],
            options={
                'db_table': 'dgmTypeEffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evegraphics',
            fields=[
                ('graphicid', models.IntegerField(db_column='graphicID', primary_key=True, serialize=False)),
                ('soffactionname', models.CharField(blank=True, db_column='sofFactionName', max_length=100, null=True)),
                ('graphicfile', models.CharField(blank=True, db_column='graphicFile', max_length=100, null=True)),
                ('sofhullname', models.CharField(blank=True, db_column='sofHullName', max_length=100, null=True)),
                ('sofracename', models.CharField(blank=True, db_column='sofRaceName', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eveGraphics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eveicons',
            fields=[
                ('iconid', models.IntegerField(db_column='iconID', primary_key=True, serialize=False)),
                ('iconfile', models.CharField(blank=True, db_column='iconFile', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eveIcons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eveunits',
            fields=[
                ('unitid', models.IntegerField(db_column='unitID', primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, db_column='unitName', max_length=100, null=True)),
                ('displayname', models.CharField(blank=True, db_column='displayName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'eveUnits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivity',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('activityid', models.IntegerField(db_column='activityID')),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industryActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivitymaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('materialtypeid', models.IntegerField(blank=True, db_column='materialTypeID', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industryActivityMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityprobabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('producttypeid', models.IntegerField(blank=True, db_column='productTypeID', null=True)),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'industryActivityProbabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('producttypeid', models.IntegerField(blank=True, db_column='productTypeID', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industryActivityProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityraces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('producttypeid', models.IntegerField(blank=True, db_column='productTypeID', null=True)),
                ('raceid', models.IntegerField(blank=True, db_column='raceID', null=True)),
            ],
            options={
                'db_table': 'industryActivityRaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('skillid', models.IntegerField(blank=True, db_column='skillID', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industryActivitySkills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryblueprints',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('maxproductionlimit', models.IntegerField(blank=True, db_column='maxProductionLimit', null=True)),
            ],
            options={
                'db_table': 'industryBlueprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcategories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=100, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontrabandtypes',
            fields=[
                ('factionid', models.IntegerField(db_column='factionID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='typeID')),
                ('standingloss', models.FloatField(blank=True, db_column='standingLoss', null=True)),
                ('confiscateminsec', models.FloatField(blank=True, db_column='confiscateMinSec', null=True)),
                ('finebyvalue', models.FloatField(blank=True, db_column='fineByValue', null=True)),
                ('attackminsec', models.FloatField(blank=True, db_column='attackMinSec', null=True)),
            ],
            options={
                'db_table': 'invContrabandTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontroltowerresourcepurposes',
            fields=[
                ('purpose', models.IntegerField(primary_key=True, serialize=False)),
                ('purposetext', models.CharField(blank=True, db_column='purposeText', max_length=100, null=True)),
            ],
            options={
                'db_table': 'invControlTowerResourcePurposes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontroltowerresources',
            fields=[
                ('controltowertypeid', models.IntegerField(db_column='controlTowerTypeID', primary_key=True, serialize=False)),
                ('resourcetypeid', models.IntegerField(db_column='resourceTypeID')),
                ('purpose', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('minsecuritylevel', models.FloatField(blank=True, db_column='minSecurityLevel', null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
            ],
            options={
                'db_table': 'invControlTowerResources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invflags',
            fields=[
                ('flagid', models.IntegerField(db_column='flagID', primary_key=True, serialize=False)),
                ('flagname', models.CharField(blank=True, db_column='flagName', max_length=200, null=True)),
                ('flagtext', models.CharField(blank=True, db_column='flagText', max_length=100, null=True)),
                ('orderid', models.IntegerField(blank=True, db_column='orderID', null=True)),
            ],
            options={
                'db_table': 'invFlags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invgroups',
            fields=[
                ('groupid', models.IntegerField(db_column='groupID', primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryID', null=True)),
                ('groupname', models.CharField(blank=True, db_column='groupName', max_length=100, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('usebaseprice', models.IntegerField(blank=True, db_column='useBasePrice', null=True)),
                ('anchored', models.IntegerField(blank=True, null=True)),
                ('anchorable', models.IntegerField(blank=True, null=True)),
                ('fittablenonsingleton', models.IntegerField(blank=True, db_column='fittableNonSingleton', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invitems',
            fields=[
                ('itemid', models.IntegerField(db_column='itemID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='typeID')),
                ('ownerid', models.IntegerField(db_column='ownerID')),
                ('locationid', models.IntegerField(db_column='locationID')),
                ('flagid', models.IntegerField(db_column='flagID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'invItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmarketgroups',
            fields=[
                ('marketgroupid', models.IntegerField(db_column='marketGroupID', primary_key=True, serialize=False)),
                ('parentgroupid', models.IntegerField(blank=True, db_column='parentGroupID', null=True)),
                ('marketgroupname', models.CharField(blank=True, db_column='marketGroupName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('hastypes', models.IntegerField(blank=True, db_column='hasTypes', null=True)),
            ],
            options={
                'db_table': 'invMarketGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmetagroups',
            fields=[
                ('metagroupid', models.IntegerField(db_column='metaGroupID', primary_key=True, serialize=False)),
                ('metagroupname', models.CharField(blank=True, db_column='metaGroupName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
            ],
            options={
                'db_table': 'invMetaGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmetatypes',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('parenttypeid', models.IntegerField(blank=True, db_column='parentTypeID', null=True)),
                ('metagroupid', models.IntegerField(blank=True, db_column='metaGroupID', null=True)),
            ],
            options={
                'db_table': 'invMetaTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invnames',
            fields=[
                ('itemid', models.IntegerField(db_column='itemID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='itemName', max_length=200)),
            ],
            options={
                'db_table': 'invNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invpositions',
            fields=[
                ('itemid', models.IntegerField(db_column='itemID', primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('yaw', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invPositions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtraits',
            fields=[
                ('traitid', models.AutoField(db_column='traitID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('skillid', models.IntegerField(blank=True, db_column='skillID', null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('bonustext', models.TextField(blank=True, db_column='bonusText', null=True)),
                ('unitid', models.IntegerField(blank=True, db_column='unitID', null=True)),
            ],
            options={
                'db_table': 'invTraits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypematerials',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('materialtypeid', models.IntegerField(db_column='materialTypeID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'invTypeMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypereactions',
            fields=[
                ('reactiontypeid', models.IntegerField(db_column='reactionTypeID', primary_key=True, serialize=False)),
                ('input', models.IntegerField()),
                ('typeid', models.IntegerField(db_column='typeID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invTypeReactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypes',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(blank=True, db_column='groupID', null=True)),
                ('typename', models.CharField(blank=True, db_column='typeName', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('portionsize', models.IntegerField(blank=True, db_column='portionSize', null=True)),
                ('raceid', models.IntegerField(blank=True, db_column='raceID', null=True)),
                ('baseprice', models.DecimalField(blank=True, db_column='basePrice', decimal_places=4, max_digits=19, null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
                ('marketgroupid', models.IntegerField(blank=True, db_column='marketGroupID', null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('soundid', models.IntegerField(blank=True, db_column='soundID', null=True)),
                ('graphicid', models.IntegerField(blank=True, db_column='graphicID', null=True)),
            ],
            options={
                'db_table': 'invTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invuniquenames',
            fields=[
                ('itemid', models.IntegerField(db_column='itemID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='itemName', max_length=200, unique=True)),
                ('groupid', models.IntegerField(blank=True, db_column='groupID', null=True)),
            ],
            options={
                'db_table': 'invUniqueNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invvolumes',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invVolumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapcelestialstatistics',
            fields=[
                ('celestialid', models.IntegerField(db_column='celestialID', primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('spectralclass', models.CharField(blank=True, db_column='spectralClass', max_length=10, null=True)),
                ('luminosity', models.FloatField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('life', models.FloatField(blank=True, null=True)),
                ('orbitradius', models.FloatField(blank=True, db_column='orbitRadius', null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('massdust', models.FloatField(blank=True, db_column='massDust', null=True)),
                ('massgas', models.FloatField(blank=True, db_column='massGas', null=True)),
                ('fragmented', models.IntegerField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('surfacegravity', models.FloatField(blank=True, db_column='surfaceGravity', null=True)),
                ('escapevelocity', models.FloatField(blank=True, db_column='escapeVelocity', null=True)),
                ('orbitperiod', models.FloatField(blank=True, db_column='orbitPeriod', null=True)),
                ('rotationrate', models.FloatField(blank=True, db_column='rotationRate', null=True)),
                ('locked', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapCelestialStatistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapconstellationjumps',
            fields=[
                ('fromregionid', models.IntegerField(blank=True, db_column='fromRegionID', null=True)),
                ('fromconstellationid', models.IntegerField(db_column='fromConstellationID', primary_key=True, serialize=False)),
                ('toconstellationid', models.IntegerField(db_column='toConstellationID')),
                ('toregionid', models.IntegerField(blank=True, db_column='toRegionID', null=True)),
            ],
            options={
                'db_table': 'mapConstellationJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapconstellations',
            fields=[
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
                ('constellationid', models.IntegerField(db_column='constellationID', primary_key=True, serialize=False)),
                ('constellationname', models.CharField(blank=True, db_column='constellationName', max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('xmin', models.FloatField(blank=True, db_column='xMin', null=True)),
                ('xmax', models.FloatField(blank=True, db_column='xMax', null=True)),
                ('ymin', models.FloatField(blank=True, db_column='yMin', null=True)),
                ('ymax', models.FloatField(blank=True, db_column='yMax', null=True)),
                ('zmin', models.FloatField(blank=True, db_column='zMin', null=True)),
                ('zmax', models.FloatField(blank=True, db_column='zMax', null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapConstellations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapdenormalize',
            fields=[
                ('itemid', models.IntegerField(db_column='itemID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('groupid', models.IntegerField(blank=True, db_column='groupID', null=True)),
                ('solarsystemid', models.IntegerField(blank=True, db_column='solarSystemID', null=True)),
                ('constellationid', models.IntegerField(blank=True, db_column='constellationID', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
                ('orbitid', models.IntegerField(blank=True, db_column='orbitID', null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('itemname', models.CharField(blank=True, db_column='itemName', max_length=100, null=True)),
                ('security', models.FloatField(blank=True, null=True)),
                ('celestialindex', models.IntegerField(blank=True, db_column='celestialIndex', null=True)),
                ('orbitindex', models.IntegerField(blank=True, db_column='orbitIndex', null=True)),
            ],
            options={
                'db_table': 'mapDenormalize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapjumps',
            fields=[
                ('stargateid', models.IntegerField(db_column='stargateID', primary_key=True, serialize=False)),
                ('destinationid', models.IntegerField(blank=True, db_column='destinationID', null=True)),
            ],
            options={
                'db_table': 'mapJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplandmarks',
            fields=[
                ('landmarkid', models.IntegerField(db_column='landmarkID', primary_key=True, serialize=False)),
                ('landmarkname', models.CharField(blank=True, db_column='landmarkName', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('locationid', models.IntegerField(blank=True, db_column='locationID', null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
            ],
            options={
                'db_table': 'mapLandmarks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplocationscenes',
            fields=[
                ('locationid', models.IntegerField(db_column='locationID', primary_key=True, serialize=False)),
                ('graphicid', models.IntegerField(blank=True, db_column='graphicID', null=True)),
            ],
            options={
                'db_table': 'mapLocationScenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplocationwormholeclasses',
            fields=[
                ('locationid', models.IntegerField(db_column='locationID', primary_key=True, serialize=False)),
                ('wormholeclassid', models.IntegerField(blank=True, db_column='wormholeClassID', null=True)),
            ],
            options={
                'db_table': 'mapLocationWormholeClasses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapregionjumps',
            fields=[
                ('fromregionid', models.IntegerField(db_column='fromRegionID', primary_key=True, serialize=False)),
                ('toregionid', models.IntegerField(db_column='toRegionID')),
            ],
            options={
                'db_table': 'mapRegionJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapregions',
            fields=[
                ('regionid', models.IntegerField(db_column='regionID', primary_key=True, serialize=False)),
                ('regionname', models.CharField(blank=True, db_column='regionName', max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('xmin', models.FloatField(blank=True, db_column='xMin', null=True)),
                ('xmax', models.FloatField(blank=True, db_column='xMax', null=True)),
                ('ymin', models.FloatField(blank=True, db_column='yMin', null=True)),
                ('ymax', models.FloatField(blank=True, db_column='yMax', null=True)),
                ('zmin', models.FloatField(blank=True, db_column='zMin', null=True)),
                ('zmax', models.FloatField(blank=True, db_column='zMax', null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapRegions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapsolarsystemjumps',
            fields=[
                ('fromregionid', models.IntegerField(blank=True, db_column='fromRegionID', null=True)),
                ('fromconstellationid', models.IntegerField(blank=True, db_column='fromConstellationID', null=True)),
                ('fromsolarsystemid', models.IntegerField(db_column='fromSolarSystemID', primary_key=True, serialize=False)),
                ('tosolarsystemid', models.IntegerField(db_column='toSolarSystemID')),
                ('toconstellationid', models.IntegerField(blank=True, db_column='toConstellationID', null=True)),
                ('toregionid', models.IntegerField(blank=True, db_column='toRegionID', null=True)),
            ],
            options={
                'db_table': 'mapSolarSystemJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapsolarsystems',
            fields=[
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
                ('constellationid', models.IntegerField(blank=True, db_column='constellationID', null=True)),
                ('solarsystemid', models.IntegerField(db_column='solarSystemID', primary_key=True, serialize=False)),
                ('solarsystemname', models.CharField(blank=True, db_column='solarSystemName', max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('xmin', models.FloatField(blank=True, db_column='xMin', null=True)),
                ('xmax', models.FloatField(blank=True, db_column='xMax', null=True)),
                ('ymin', models.FloatField(blank=True, db_column='yMin', null=True)),
                ('ymax', models.FloatField(blank=True, db_column='yMax', null=True)),
                ('zmin', models.FloatField(blank=True, db_column='zMin', null=True)),
                ('zmax', models.FloatField(blank=True, db_column='zMax', null=True)),
                ('luminosity', models.FloatField(blank=True, null=True)),
                ('border', models.IntegerField(blank=True, null=True)),
                ('fringe', models.IntegerField(blank=True, null=True)),
                ('corridor', models.IntegerField(blank=True, null=True)),
                ('hub', models.IntegerField(blank=True, null=True)),
                ('international', models.IntegerField(blank=True, null=True)),
                ('regional', models.IntegerField(blank=True, null=True)),
                ('constellation', models.IntegerField(blank=True, null=True)),
                ('security', models.FloatField(blank=True, null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('suntypeid', models.IntegerField(blank=True, db_column='sunTypeID', null=True)),
                ('securityclass', models.CharField(blank=True, db_column='securityClass', max_length=2, null=True)),
            ],
            options={
                'db_table': 'mapSolarSystems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapuniverse',
            fields=[
                ('universeid', models.IntegerField(db_column='universeID', primary_key=True, serialize=False)),
                ('universename', models.CharField(blank=True, db_column='universeName', max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('xmin', models.FloatField(blank=True, db_column='xMin', null=True)),
                ('xmax', models.FloatField(blank=True, db_column='xMax', null=True)),
                ('ymin', models.FloatField(blank=True, db_column='yMin', null=True)),
                ('ymax', models.FloatField(blank=True, db_column='yMax', null=True)),
                ('zmin', models.FloatField(blank=True, db_column='zMin', null=True)),
                ('zmax', models.FloatField(blank=True, db_column='zMax', null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapUniverse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematics',
            fields=[
                ('schematicid', models.IntegerField(db_column='schematicID', primary_key=True, serialize=False)),
                ('schematicname', models.CharField(blank=True, db_column='schematicName', max_length=255, null=True)),
                ('cycletime', models.IntegerField(blank=True, db_column='cycleTime', null=True)),
            ],
            options={
                'db_table': 'planetSchematics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematicspinmap',
            fields=[
                ('schematicid', models.IntegerField(db_column='schematicID', primary_key=True, serialize=False)),
                ('pintypeid', models.IntegerField(db_column='pinTypeID')),
            ],
            options={
                'db_table': 'planetSchematicsPinMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematicstypemap',
            fields=[
                ('schematicid', models.IntegerField(db_column='schematicID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='typeID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('isinput', models.IntegerField(blank=True, db_column='isInput', null=True)),
            ],
            options={
                'db_table': 'planetSchematicsTypeMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramactivities',
            fields=[
                ('activityid', models.IntegerField(db_column='activityID', primary_key=True, serialize=False)),
                ('activityname', models.CharField(blank=True, db_column='activityName', max_length=100, null=True)),
                ('iconno', models.CharField(blank=True, db_column='iconNo', max_length=5, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ramActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinestations',
            fields=[
                ('stationid', models.IntegerField(db_column='stationID', primary_key=True, serialize=False)),
                ('assemblylinetypeid', models.IntegerField(db_column='assemblyLineTypeID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stationtypeid', models.IntegerField(blank=True, db_column='stationTypeID', null=True)),
                ('ownerid', models.IntegerField(blank=True, db_column='ownerID', null=True)),
                ('solarsystemid', models.IntegerField(blank=True, db_column='solarSystemID', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypedetailpercategory',
            fields=[
                ('assemblylinetypeid', models.IntegerField(db_column='assemblyLineTypeID', primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField(db_column='categoryID')),
                ('timemultiplier', models.FloatField(blank=True, db_column='timeMultiplier', null=True)),
                ('materialmultiplier', models.FloatField(blank=True, db_column='materialMultiplier', null=True)),
                ('costmultiplier', models.FloatField(blank=True, db_column='costMultiplier', null=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypeDetailPerCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypedetailpergroup',
            fields=[
                ('assemblylinetypeid', models.IntegerField(db_column='assemblyLineTypeID', primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(db_column='groupID')),
                ('timemultiplier', models.FloatField(blank=True, db_column='timeMultiplier', null=True)),
                ('materialmultiplier', models.FloatField(blank=True, db_column='materialMultiplier', null=True)),
                ('costmultiplier', models.FloatField(blank=True, db_column='costMultiplier', null=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypeDetailPerGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypes',
            fields=[
                ('assemblylinetypeid', models.IntegerField(db_column='assemblyLineTypeID', primary_key=True, serialize=False)),
                ('assemblylinetypename', models.CharField(blank=True, db_column='assemblyLineTypeName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('basetimemultiplier', models.FloatField(blank=True, db_column='baseTimeMultiplier', null=True)),
                ('basematerialmultiplier', models.FloatField(blank=True, db_column='baseMaterialMultiplier', null=True)),
                ('basecostmultiplier', models.FloatField(blank=True, db_column='baseCostMultiplier', null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('mincostperhour', models.FloatField(blank=True, db_column='minCostPerHour', null=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raminstallationtypecontents',
            fields=[
                ('installationtypeid', models.IntegerField(db_column='installationTypeID', primary_key=True, serialize=False)),
                ('assemblylinetypeid', models.IntegerField(db_column='assemblyLineTypeID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ramInstallationTypeContents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skinlicense',
            fields=[
                ('licensetypeid', models.IntegerField(db_column='licenseTypeID', primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('skinid', models.IntegerField(blank=True, db_column='skinID', null=True)),
            ],
            options={
                'db_table': 'skinLicense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skinmaterials',
            fields=[
                ('skinmaterialid', models.IntegerField(db_column='skinMaterialID', primary_key=True, serialize=False)),
                ('displaynameid', models.IntegerField(blank=True, db_column='displayNameID', null=True)),
                ('materialsetid', models.IntegerField(blank=True, db_column='materialSetID', null=True)),
            ],
            options={
                'db_table': 'skinMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('skinid', models.IntegerField(db_column='skinID', primary_key=True, serialize=False)),
                ('internalname', models.CharField(blank=True, db_column='internalName', max_length=70, null=True)),
                ('skinmaterialid', models.IntegerField(blank=True, db_column='skinMaterialID', null=True)),
            ],
            options={
                'db_table': 'skins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skinship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinid', models.IntegerField(blank=True, db_column='skinID', null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
            ],
            options={
                'db_table': 'skinShip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staoperations',
            fields=[
                ('activityid', models.IntegerField(blank=True, db_column='activityID', null=True)),
                ('operationid', models.IntegerField(db_column='operationID', primary_key=True, serialize=False)),
                ('operationname', models.CharField(blank=True, db_column='operationName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('fringe', models.IntegerField(blank=True, null=True)),
                ('corridor', models.IntegerField(blank=True, null=True)),
                ('hub', models.IntegerField(blank=True, null=True)),
                ('border', models.IntegerField(blank=True, null=True)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('caldaristationtypeid', models.IntegerField(blank=True, db_column='caldariStationTypeID', null=True)),
                ('minmatarstationtypeid', models.IntegerField(blank=True, db_column='minmatarStationTypeID', null=True)),
                ('amarrstationtypeid', models.IntegerField(blank=True, db_column='amarrStationTypeID', null=True)),
                ('gallentestationtypeid', models.IntegerField(blank=True, db_column='gallenteStationTypeID', null=True)),
                ('jovestationtypeid', models.IntegerField(blank=True, db_column='joveStationTypeID', null=True)),
            ],
            options={
                'db_table': 'staOperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staoperationservices',
            fields=[
                ('operationid', models.IntegerField(db_column='operationID', primary_key=True, serialize=False)),
                ('serviceid', models.IntegerField(db_column='serviceID')),
            ],
            options={
                'db_table': 'staOperationServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staservices',
            fields=[
                ('serviceid', models.IntegerField(db_column='serviceID', primary_key=True, serialize=False)),
                ('servicename', models.CharField(blank=True, db_column='serviceName', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'staServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stastations',
            fields=[
                ('stationid', models.BigIntegerField(db_column='stationID', primary_key=True, serialize=False)),
                ('security', models.FloatField(blank=True, null=True)),
                ('dockingcostpervolume', models.FloatField(blank=True, db_column='dockingCostPerVolume', null=True)),
                ('maxshipvolumedockable', models.FloatField(blank=True, db_column='maxShipVolumeDockable', null=True)),
                ('officerentalcost', models.IntegerField(blank=True, db_column='officeRentalCost', null=True)),
                ('operationid', models.IntegerField(blank=True, db_column='operationID', null=True)),
                ('stationtypeid', models.IntegerField(blank=True, db_column='stationTypeID', null=True)),
                ('corporationid', models.IntegerField(blank=True, db_column='corporationID', null=True)),
                ('solarsystemid', models.IntegerField(blank=True, db_column='solarSystemID', null=True)),
                ('constellationid', models.IntegerField(blank=True, db_column='constellationID', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
                ('stationname', models.CharField(blank=True, db_column='stationName', max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('reprocessingefficiency', models.FloatField(blank=True, db_column='reprocessingEfficiency', null=True)),
                ('reprocessingstationstake', models.FloatField(blank=True, db_column='reprocessingStationsTake', null=True)),
                ('reprocessinghangarflag', models.IntegerField(blank=True, db_column='reprocessingHangarFlag', null=True)),
            ],
            options={
                'db_table': 'staStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stastationtypes',
            fields=[
                ('stationtypeid', models.IntegerField(db_column='stationTypeID', primary_key=True, serialize=False)),
                ('dockentryx', models.FloatField(blank=True, db_column='dockEntryX', null=True)),
                ('dockentryy', models.FloatField(blank=True, db_column='dockEntryY', null=True)),
                ('dockentryz', models.FloatField(blank=True, db_column='dockEntryZ', null=True)),
                ('dockorientationx', models.FloatField(blank=True, db_column='dockOrientationX', null=True)),
                ('dockorientationy', models.FloatField(blank=True, db_column='dockOrientationY', null=True)),
                ('dockorientationz', models.FloatField(blank=True, db_column='dockOrientationZ', null=True)),
                ('operationid', models.IntegerField(blank=True, db_column='operationID', null=True)),
                ('officeslots', models.IntegerField(blank=True, db_column='officeSlots', null=True)),
                ('reprocessingefficiency', models.FloatField(blank=True, db_column='reprocessingEfficiency', null=True)),
                ('conquerable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staStationTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translationtables',
            fields=[
                ('sourcetable', models.CharField(db_column='sourceTable', max_length=200, primary_key=True, serialize=False)),
                ('destinationtable', models.CharField(blank=True, db_column='destinationTable', max_length=200, null=True)),
                ('translatedkey', models.CharField(db_column='translatedKey', max_length=200)),
                ('tcgroupid', models.IntegerField(blank=True, db_column='tcGroupID', null=True)),
                ('tcid', models.IntegerField(blank=True, db_column='tcID', null=True)),
            ],
            options={
                'db_table': 'translationTables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslationcolumns',
            fields=[
                ('tcgroupid', models.IntegerField(blank=True, db_column='tcGroupID', null=True)),
                ('tcid', models.IntegerField(db_column='tcID', primary_key=True, serialize=False)),
                ('tablename', models.CharField(db_column='tableName', max_length=256)),
                ('columnname', models.CharField(db_column='columnName', max_length=128)),
                ('masterid', models.CharField(blank=True, db_column='masterID', max_length=128, null=True)),
            ],
            options={
                'db_table': 'trnTranslationColumns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslationlanguages',
            fields=[
                ('numericlanguageid', models.IntegerField(db_column='numericLanguageID', primary_key=True, serialize=False)),
                ('languageid', models.CharField(blank=True, db_column='languageID', max_length=50, null=True)),
                ('languagename', models.CharField(blank=True, db_column='languageName', max_length=200, null=True)),
            ],
            options={
                'db_table': 'trnTranslationLanguages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslations',
            fields=[
                ('tcid', models.IntegerField(db_column='tcID', primary_key=True, serialize=False)),
                ('keyid', models.IntegerField(db_column='keyID')),
                ('languageid', models.CharField(db_column='languageID', max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'trnTranslations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warcombatzones',
            fields=[
                ('combatzoneid', models.IntegerField(db_column='combatZoneID', primary_key=True, serialize=False)),
                ('combatzonename', models.CharField(blank=True, db_column='combatZoneName', max_length=100, null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('centersystemid', models.IntegerField(blank=True, db_column='centerSystemID', null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'warCombatZones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warcombatzonesystems',
            fields=[
                ('solarsystemid', models.IntegerField(db_column='solarSystemID', primary_key=True, serialize=False)),
                ('combatzoneid', models.IntegerField(blank=True, db_column='combatZoneID', null=True)),
            ],
            options={
                'db_table': 'warCombatZoneSystems',
                'managed': False,
            },
        ),
    ]
